export const NE = {
  SERVER: {
    NAME: '@mhdd_24/netextender-mcp',
    VERSION: '1.0.1',
    STARTUP_MESSAGE: 'NetExtender MCP Server Started',
    FATAL_PREFIX: 'Fatal error:',
  },
  CLI: {
    DEFAULT_WINDOWS_PATHS: [
      'C:/Program Files/SonicWall/SSL-VPN/NetExtender/nxcli.exe',
      'C:/Program Files (x86)/SonicWall/SSL-VPN/NetExtender/nxcli.exe',
      'C:/Program Files/SonicWall/SSL-VPN/NetExtender/necli.exe',
      'C:/Program Files (x86)/SonicWall/SSL-VPN/NetExtender/necli.exe',
    ] as const,
    CONNECTED_MARKER: 'NetExtender has been connected',
    DISCONNECTED_MARKER: 'NetExtender is not connected',
    DEFAULT_TIMEOUT_MS: 120_000 as number,
    LIST_TIMEOUT_MS: 30_000 as number,
    STATUS_TIMEOUT_MS: 20_000 as number,
    CONNECT_POLL_INTERVAL_MS: 2_000 as number,
    CONNECT_POLL_TIMEOUT_MS: 180_000 as number,
    CONNECT_INTERACTIVE_TIMEOUT_MS: 180_000 as number,
  },
  ENV: {
    CLI_KEYS: ['NETEXTENDER_CLI', 'NETEXTENDER_EXE', 'NXCLI_EXE'] as const,
    PROFILE_KEYS: ['NETEXTENDER_PROFILE', 'NETEXTENDER_CONNECTION', 'VPN_PROFILE'] as const,
    SERVER_KEYS: ['NETEXTENDER_SERVER', 'VPN_SERVER'] as const,
    DOMAIN_KEYS: ['NETEXTENDER_DOMAIN', 'VPN_DOMAIN'] as const,
    USERNAME_KEYS: ['NETEXTENDER_USERNAME', 'VPN_USERNAME'] as const,
    PASSWORD_KEYS: ['NETEXTENDER_PASSWORD', 'VPN_PASSWORD'] as const,
    ALWAYS_TRUST_KEYS: ['NETEXTENDER_ALWAYS_TRUST', 'VPN_ALWAYS_TRUST'] as const,
  },
  TOOLS: {
    STATUS: {
      NAME: 'vpn_status',
      DESCRIPTION: 'Check SonicWall NetExtender VPN connection status via nxcli. Returns connected/disconnected state and session details when connected.',
      FAILURE: 'vpn_status failed',
    },
    LIST_PROFILES: {
      NAME: 'list_vpn_profiles',
      DESCRIPTION: 'List saved NetExtender connection profiles via nxcli connection list.',
      PROFILE_DESCRIPTION: 'Optional profile name filter.',
      FAILURE: 'list_vpn_profiles failed',
    },
    CONNECT: {
      NAME: 'vpn_connect',
      DESCRIPTION: 'Connect to SonicWall NetExtender VPN. Credentials and certificate trust are handled automatically; you are only prompted for OTP when required.',
      PROFILE_DESCRIPTION: 'Connection profile name. Defaults to NETEXTENDER_PROFILE.',
      SERVER_DESCRIPTION: 'VPN server host[:port]. Defaults to NETEXTENDER_SERVER.',
      DOMAIN_DESCRIPTION: 'VPN domain. Defaults to NETEXTENDER_DOMAIN.',
      USERNAME_DESCRIPTION: 'VPN username. Defaults to NETEXTENDER_USERNAME.',
      PASSWORD_DESCRIPTION: 'VPN password. Defaults to NETEXTENDER_PASSWORD.',
      OTP_DESCRIPTION: 'Optional OTP code. If omitted and OTP is required, a dialog prompts you to enter it.',
      ALWAYS_TRUST_DESCRIPTION: 'Pass --always-trust when creating/updating the saved profile.',
      WAITING_FOR_OTP: 'OTP required — enter the code in the dialog, then connection will complete automatically.',
      SUCCESS: 'VPN connected',
      ALREADY_CONNECTED: 'VPN is already connected',
      FAILURE: 'vpn_connect failed',
    },
    DISCONNECT: {
      NAME: 'vpn_disconnect',
      DESCRIPTION: 'Disconnect the active SonicWall NetExtender VPN session via nxcli disconnect.',
      SUCCESS: 'VPN disconnected',
      NOT_CONNECTED: 'VPN is not connected',
      FAILURE: 'vpn_disconnect failed',
    },
  },
  MESSAGES: {
    MISSING_CLI: 'NetExtender CLI not found. Set NETEXTENDER_CLI to nxcli.exe or install SonicWall NetExtender.',
    MISSING_PROFILE: 'profileName is required when NETEXTENDER_PROFILE is not set and server is not provided.',
    MISSING_SERVER: 'server is required when connecting without an existing profile.',
    MISSING_USERNAME: 'username is required. Set NETEXTENDER_USERNAME or pass username.',
    MISSING_PASSWORD: 'password is required. Set NETEXTENDER_PASSWORD or pass password.',
    MISSING_DOMAIN: 'domain is required when creating/updating a profile. Set NETEXTENDER_DOMAIN or pass domain.',
    GENERIC_ERROR_PREFIX: 'Error:',
    CLI_FAILED_PREFIX: 'nxcli failed',
    CONNECT_TIMEOUT: 'Timed out waiting for VPN to connect after OTP entry.',
  },
} as const;
